[project]
name = 'Decentralized-Biodiversity-Conservation-and-Species-Protection-Network'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.ecosystem-services]
path = 'contracts/ecosystem-services.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
